name: "Withings Sync"
version: "1.1.1"
slug: withings_sync
description: "Sync Withings weight data to Garmin Connect"
url: "https://github.com/mcinteerj/ha-addons"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:scale-bathroom
map:
  - config:rw
options:
  garmin_username: ""
  garmin_password: ""
schema:
  garmin_username: str
  garmin_password: password
