name: "Withings Sync"
version: "1.0.2"
slug: withings_sync
description: "Sync Withings weight data to Garmin Connect"
url: "https://github.com/mcinteerj/ha-addons"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: once
boot: manual
map:
  - config:rw
options:
  garmin_username: ""
  garmin_password: ""
schema:
  garmin_username: str
  garmin_password: password
