name: "Withings Sync"
version: "1.4.0"
slug: withings_sync
description: "Sync Withings weight data to Garmin Connect"
url: "https://github.com/mcinteerj/ha-addons"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:scale-bathroom
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Sync API for automations"
